apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: file-sharing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nazim112/front-end:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://backend:63891/api"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: file-sharing
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001